### ISSUE TITLE
How to know which version of tokio should be used.

### ISSUE THREAD

**Issue by wotori** [Joylei/eip-rs#12]
Have just tried your library, stuck with setting up the dependencies, which tokio should be used?
Would be cool to have examples that can be run out of the box

**Comment by wotori** [comment]
would be nice to add smth like that to the doc as needed dependencies for examples at least
anyhow = "1.0.69"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }

**Comment by Joylei** [comment]
You do not need to know the exactly version used. The major version will work.
