### ISSUE TITLE
How to read SLC 500 addresses?

### ISSUE THREAD

**Issue by zagdrath** [Joylei/eip-rs#16]
I was just wondering how I would read an address like `O:1/0` from a SLC 500 style PLC. Trying to use something like this `let tag = EPath::parse_tag("O:1/0")?;` does not work.

**Comment by Joylei** [comment]
The library does not work with SLC 500 style PLC. It requires PCCC which is not supported by this library.

**Comment by zagdrath** [comment]
Would you ever be interested in adding PCCC support to this library? Or does your libplctag wrapper support it?

**Comment by Joylei** [comment]
> Would you ever be interested in adding PCCC support to this library?

No plan for PCCC at the moment.

> Or does your libplctag wrapper support it?

yes, libplctag wrapper supports it
