### ISSUE TITLE
Question: Can eip-rs Read UDTs?

### ISSUE THREAD

**Issue by TheColonel2688** [Joylei/eip-rs#20]
Can eip-rs Read and Write UDTs? 

I need a grab a UDT instance from my CompactLogix PLCs, can that be done? And then Mapped to a struct?

Example UDT on PLC

```
- Type: MyUDT
  - MyDint1 : DINT
  - MyDint2: DINT
  - MyString1 : STRING
  - MyString2 : STRING
```
  
Path to an instance on PLC that is in Program1
  \Program1.MyUdtInstance1
  
Rust Type: 
```
struct MyUDT {
    MyDint1: i32,
    MyDint2: i32,
    MyString1 : String
    MyString2 : String
}
```

**Comment by Joylei** [comment]
the lib can read UDT, please check examples
 in the repo.

**Comment by TheColonel2688** [comment]
I don't see examples of fetching a UDT instance, I only see an example of reading individual tags that ate in side a UDT, but not the whole UDT.

Could you direct me to the example you are talking about?

**Comment by klmurphy72** [comment]
Check out ab-tag-read-fragmented.rs.  It reads a UDT full of strings.
